services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock
    environment:
      EULA: "TRUE"
      TZ: "America/New_York"
      SERVER_NAME: "Valdrakken"
      GAMEMODE: "survival"
      DIFFICULTY: $DIFFICULTY
      MAX_PLAYERS: 10
      ONLINE_MODE: true
      ALLOW_LIST: true
      ENABLE_LAN_VISIBILITY: true
      VIEW_DISTANCE: 32
      TICK_DISTANCE: 4
      PLAYER_IDLE_TIMEOUT: 0
      MAX_THREADS: 8
      LEVEL_NAME: $WORLD_NAME
      LEVEL_TYPE: "default"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
      TEXTUREPACK_REQUIRED: false
    ports:
      - "19132:19132/udp"
    volumes:
      - type: bind
        source: ../bedrock
        target: /data
    labels:
      - "traefik.http.routers.bds.rule=Host(`bds.docker.localhost`)"
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ../jellyfin/config:/config
      - ../jellyfin/cache:/cache
      - type: bind
        source: ../media
        target: /media
    stdin_open: true
    tty: true
    labels:
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.docker.localhost`)"
  reverse-proxy:
    image: traefik:v3.4
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

